services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=512M
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8082:80"  # Map port 80 on the container to port 8082 on the host
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
